"""EXP-001 Steps 11-15: Model Training, Validation Scoring, Threshold Sweep, and Official Evaluation.

1. Trains HistGradientBoostingClassifier on training pairs generated by build_training_pairs.py.
2. Scores Cap-200 candidate pairs for the fixed 100,000 validation S1 entities.
3. Sweeps probability thresholds [0.10 to 0.95 by 0.05] against the official macro F0.5 metric.
4. Computes error breakdown (blocking miss, pruning miss, model FN, model FP).
5. Saves all required artifacts in experiments/EXP-001/ and appends row to experiments.csv.
"""

import ctypes
import heapq
import json
import time
from ctypes import wintypes

import joblib
import numpy as np
import pandas as pd
from rapidfuzz import fuzz
from sklearn.ensemble import HistGradientBoostingClassifier

from blocking import RareTokenIndex
from features import FEATURE_NAMES
from io_utils import explode_ground_truth, load_ground_truth
from metrics import macro_fbeta
from paths import PROJECT_ROOT

EXP_DIR = PROJECT_ROOT / "experiments" / "EXP-001"
CACHE = PROJECT_ROOT / "data" / "interim" / "exp001"
LOG_FILE = PROJECT_ROOT / "logs" / "train_and_evaluate.log"
CAP = 200
SEED = 42
THRESHOLDS = np.round(np.arange(0.10, 0.96, 0.05), 2)

psapi = ctypes.windll.psapi
kernel32 = ctypes.windll.kernel32


class PMC(ctypes.Structure):
    _fields_ = [
        ("cb", wintypes.DWORD),
        ("PageFaultCount", wintypes.DWORD),
        ("PeakWorkingSetSize", ctypes.c_size_t),
        ("WorkingSetSize", ctypes.c_size_t),
        ("QuotaPeakPagedPoolUsage", ctypes.c_size_t),
        ("QuotaPagedPoolUsage", ctypes.c_size_t),
        ("QuotaPeakNonPagedPoolUsage", ctypes.c_size_t),
        ("QuotaNonPagedPoolUsage", ctypes.c_size_t),
        ("PagefileUsage", ctypes.c_size_t),
        ("PeakPagefileUsage", ctypes.c_size_t),
    ]


psapi.GetProcessMemoryInfo.argtypes = [wintypes.HANDLE, ctypes.POINTER(PMC), wintypes.DWORD]
psapi.GetProcessMemoryInfo.restype = wintypes.BOOL


def get_ram_mb():
    pmc = PMC()
    pmc.cb = ctypes.sizeof(PMC)
    psapi.GetProcessMemoryInfo(kernel32.GetCurrentProcess(), ctypes.byref(pmc), pmc.cb)
    return pmc.WorkingSetSize / (1024 * 1024), pmc.PeakWorkingSetSize / (1024 * 1024)


def log(msg, to_file=True):
    print(msg, flush=True)
    if to_file:
        with open(LOG_FILE, "a", encoding="utf-8") as f:
            f.write(msg + "\n")
            f.flush()


def compute_rank_score(s1_name, s1_addr, s1_t1, s1_a1s, s1_n1s, n2, a2, name_df, addr_df):
    t2 = set(n2.split())
    a2s = set(a2.split())
    shared_n = s1_t1 & t2
    shared_a = s1_a1s & a2s
    score = 0.0
    if s1_addr and s1_addr == a2:
        score += 5.0
    if s1_name and s1_name == n2:
        score += 1.0
    if shared_n:
        min_df = min(name_df.get(t, 1) for t in shared_n)
        score += 2.0 / (1.0 + min_df) + 0.1 * len(shared_n)
    if shared_a:
        min_df = min(addr_df.get(t, 1) for t in shared_a)
        score += 2.0 / (1.0 + min_df) + 0.1 * len(shared_a)
    if s1_n1s and (s1_n1s & shared_a):
        score += 1.5
    return score


class B5Blocker:
    def __init__(self, s23: pd.DataFrame):
        self.name_idx = RareTokenIndex(s23, "name_norm")
        self.addr_idx = RareTokenIndex(s23, "address_norm")

    def candidates(self, name: str, addr: str, country: str):
        name_cand = self.name_idx.query_union(name, country, 1, country_aware=True)
        if not name_cand:
            name_cand = self.name_idx.query_union(name, country, 1, country_aware=False)
        addr_cand = self.addr_idx.query_union(addr, country, 1, country_aware=True)
        if not addr_cand:
            addr_cand = self.addr_idx.query_union(addr, country, 1, country_aware=False)
        return name_cand | addr_cand


def extract_features(name1, addr1, c1, s1_t1, s1_a1s, s1_n1s, la1, la_addr1, name2, addr2, c2, name_df, addr_df):
    t2 = set(name2.split())
    a2 = set(addr2.split())
    shared_name = s1_t1 & t2
    shared_addr = s1_a1s & a2
    n2 = {t for t in a2 if any(c.isdigit() for c in t)}

    min_df_n = float(min(name_df.get(t, 0) for t in shared_name)) if shared_name else 0.0
    min_df_a = float(min(addr_df.get(t, 0) for t in shared_addr)) if shared_addr else 0.0

    la2 = len(name2)
    name_len_ratio = min(la1, la2) / max(la1, la2) if max(la1, la2) else 0.0
    la_addr2 = len(addr2)
    addr_len_ratio = min(la_addr1, la_addr2) / max(la_addr1, la_addr2) if max(la_addr1, la_addr2) else 0.0

    u_n = s1_t1 | t2
    u_a = s1_a1s | a2
    u_num = s1_n1s | n2
    i_num = s1_n1s & n2

    return [
        1.0 if (name1 and name1 == name2) else 0.0,
        len(shared_name) / len(u_n) if u_n else 1.0,
        len(shared_name) / min(len(s1_t1), len(t2)) if (s1_t1 and t2) else 0.0,
        fuzz.ratio(name1, name2) if (name1 or name2) else 0.0,
        fuzz.token_set_ratio(name1, name2) if (name1 or name2) else 0.0,
        name_len_ratio,
        float(len(shared_name)),
        min_df_n,
        1.0 if (addr1 and addr1 == addr2) else 0.0,
        len(shared_addr) / len(u_a) if u_a else 1.0,
        len(shared_addr) / min(len(s1_a1s), len(a2)) if (s1_a1s and a2) else 0.0,
        fuzz.ratio(addr1, addr2) if (addr1 or addr2) else 0.0,
        fuzz.token_set_ratio(addr1, addr2) if (addr1 or addr2) else 0.0,
        addr_len_ratio,
        float(len(shared_addr)),
        min_df_a,
        float(len(i_num)),
        len(i_num) / len(u_num) if u_num else 1.0,
        1.0 if (s1_n1s and n2 and not i_num) else 0.0,
        1.0 if c1 == c2 else 0.0,
        1.0 if not name1 else 0.0,
        1.0 if not addr1 else 0.0,
    ]


def load_val():
    val_ids = pd.read_csv(EXP_DIR / "validation_s1_ids.csv")
    s1 = pd.read_parquet(CACHE / "train_s1.parquet")
    s1 = s1[s1.entity_id.isin(set(val_ids.entity_id))].reset_index(drop=True)
    return s1


def load_s23():
    cols = ["entity_id", "name_norm", "address_norm", "country"]
    s2 = pd.read_parquet(CACHE / "train_s2.parquet", columns=cols)
    s3 = pd.read_parquet(CACHE / "train_s3.parquet", columns=cols)
    return pd.concat([s2, s3], ignore_index=True)


def truth_map(s1):
    gt = load_ground_truth()
    long = explode_ground_truth(gt)
    ids = set(s1.entity_id.astype(object))
    long = long[long.source1_entity_id.astype(object).isin(ids)]
    truth = {sid: set() for sid in ids}
    for sid, mid in zip(long.source1_entity_id.astype(object), long.matched_id.astype(object)):
        truth[sid].add(mid)
    return truth


def main():
    with open(LOG_FILE, "w", encoding="utf-8") as f:
        f.write(
            f"=== EXP-001 Model Training & Validation Evaluation Started at {time.strftime('%Y-%m-%d %H:%M:%S')} ===\n"
        )

    t_job_start = time.time()

    # 1. Train Model
    log("\n--- Step 1: Model Training ---")
    log("Loading precomputed training data...")
    X_train = np.load(EXP_DIR / "train_X.npy")
    y_train = np.load(EXP_DIR / "train_y.npy")
    log(f"Loaded training data: shape={X_train.shape}, classes={dict(zip(*np.unique(y_train, return_counts=True)))}")

    model_config = {
        "algorithm": "HistGradientBoostingClassifier",
        "random_state": SEED,
        "max_depth": 6,
        "max_iter": 100,
        "early_stopping": "auto",
        "scoring": "loss",
    }
    with open(EXP_DIR / "model_config.json", "w", encoding="utf-8") as f:
        json.dump(model_config, f, indent=2)

    log(
        f"Training {model_config['algorithm']} (max_depth={model_config['max_depth']}, max_iter={model_config['max_iter']})..."
    )
    t_tr0 = time.time()
    clf = HistGradientBoostingClassifier(
        random_state=SEED,
        max_depth=model_config["max_depth"],
        max_iter=model_config["max_iter"],
    )
    clf.fit(X_train, y_train)
    train_time = time.time() - t_tr0
    log(f"Model trained in {train_time:.2f} s.")

    # Save model artifact
    joblib.dump(clf, EXP_DIR / "model_hgb.joblib")
    log(f"Model saved to {EXP_DIR / 'model_hgb.joblib'}")

    # Training summary
    train_summary = {
        "algorithm": model_config["algorithm"],
        "train_samples": len(X_train),
        "train_features": int(X_train.shape[1]),
        "positives": int((y_train == 1).sum()),
        "negatives": int((y_train == 0).sum()),
        "training_time_seconds": round(train_time, 2),
        "model_config": model_config,
    }
    with open(EXP_DIR / "training_summary.json", "w", encoding="utf-8") as f:
        json.dump(train_summary, f, indent=2)
    with open(EXP_DIR / "feature_list.json", "w", encoding="utf-8") as f:
        json.dump(FEATURE_NAMES, f, indent=2)

    del X_train, y_train

    # 2. Setup Validation
    log("\n--- Step 2: Validation Setup ---")
    log("Loading validation S1 (100,000 entities) and S2/S3 pools...")
    t_val_setup0 = time.time()
    s1 = load_val()
    s23 = load_s23()
    s23_lookup = dict(
        zip(
            s23.entity_id.astype(object),
            zip(s23.name_norm.astype(object), s23.address_norm.astype(object), s23.country.astype(object)),
        )
    )
    blocker = B5Blocker(s23)
    name_df = dict(blocker.name_idx.df_global)
    addr_df = dict(blocker.addr_idx.df_global)
    del s23

    truth = truth_map(s1)
    total_truth_links = sum(len(v) for v in truth.values())
    val_setup_time = time.time() - t_val_setup0
    cur_ram, peak_ram = get_ram_mb()
    log(f"Validation setup complete in {val_setup_time:.1f}s. RAM: {cur_ram:.1f} MB (Peak: {peak_ram:.1f} MB)")
    log(f"Validation set: {len(s1)} S1 entities | {total_truth_links} true positive links.")

    # 3. Score Validation Candidates
    log(f"\n--- Step 3: Candidate Scoring (Cap-{CAP}) across all 100,000 S1 ---")
    per_s1_cands = {}
    per_s1_scores = {}
    total_candidate_pairs = 0
    t_score0 = time.time()
    log_interval = 2500

    for i, (eid, name, addr, country) in enumerate(
        zip(
            s1.entity_id.astype(object),
            s1.name_norm.astype(object),
            s1.address_norm.astype(object),
            s1.country.astype(object),
        )
    ):
        cand = blocker.candidates(name, addr, country)
        s1_t1 = set(name.split())
        s1_a1s = set(addr.split())
        s1_n1s = {tok for tok in s1_a1s if any(c.isdigit() for c in tok)}
        la1, la_addr1 = len(name), len(addr)

        cand_list = list(cand)
        scores = {}
        for cid in cand_list:
            n2, a2, _ = s23_lookup[cid]
            scores[cid] = compute_rank_score(name, addr, s1_t1, s1_a1s, s1_n1s, n2, a2, name_df, addr_df)

        if len(cand_list) > CAP:
            ranked_top = heapq.nlargest(CAP, cand_list, key=scores.__getitem__)
        else:
            ranked_top = sorted(cand_list, key=lambda c: -scores[c])

        total_candidate_pairs += len(ranked_top)
        if not ranked_top:
            per_s1_cands[eid] = []
            per_s1_scores[eid] = np.array([], dtype=np.float32)
            continue

        feats = [
            extract_features(
                name,
                addr,
                country,
                s1_t1,
                s1_a1s,
                s1_n1s,
                la1,
                la_addr1,
                s23_lookup[c][0],
                s23_lookup[c][1],
                s23_lookup[c][2],
                name_df,
                addr_df,
            )
            for c in ranked_top
        ]
        proba = clf.predict_proba(np.array(feats, dtype=np.float32))[:, 1]
        per_s1_cands[eid] = ranked_top
        per_s1_scores[eid] = proba

        if (i + 1) % log_interval == 0 or (i + 1) == len(s1):
            elapsed = time.time() - t_score0
            s1_rate = (i + 1) / elapsed
            pairs_rate = total_candidate_pairs / elapsed
            eta_min = (len(s1) - (i + 1)) / max(s1_rate, 0.001) / 60.0
            cur_ram_step, peak_ram_step = get_ram_mb()
            log(
                f"[{i+1:6d}/{len(s1)}] {100*(i+1)/len(s1):5.1f}% | Elapsed: {elapsed/60:4.1f}m | Rate: {s1_rate:4.1f} S1/s ({pairs_rate:6.0f} pairs/s) | RAM: {cur_ram_step:5.1f} MB (Peak: {peak_ram_step:5.1f} MB) | ETA: {eta_min:4.1f}m"
            )

    scoring_time = time.time() - t_score0
    log(
        f"\nValidation scoring completed: {total_candidate_pairs} candidate pairs in {scoring_time/60:.2f} min ({total_candidate_pairs/scoring_time:.0f} pairs/sec)."
    )

    # 4. Threshold Sweep
    log("\n--- Step 4: Official Macro F0.5 Threshold Search ---")
    results = []
    best_th = 0.5
    best_f05 = -1.0
    best_row = None

    for th in THRESHOLDS:
        preds = {}
        total_pred_links = 0
        tp = 0
        fp = 0

        for eid, cands in per_s1_cands.items():
            sc = per_s1_scores[eid]
            p = {cid for cid, score in zip(cands, sc) if score >= th}
            preds[eid] = p
            t = truth[eid]
            tp += len(p & t)
            fp += len(p - t)
            total_pred_links += len(p)

        fn = total_truth_links - tp
        m = macro_fbeta(truth, preds)

        row = {
            "threshold": float(th),
            "macro_f0_5": round(float(m["f0_5"]), 5),
            "macro_precision": round(float(m["precision"]), 5),
            "macro_recall": round(float(m["recall"]), 5),
            "f0_5_singletons": round(float(m["f0_5_singletons"]), 5),
            "f0_5_non_singletons": round(float(m["f0_5_non_singletons"]), 5),
            "predicted_links": int(total_pred_links),
            "tp": int(tp),
            "fp": int(fp),
            "fn": int(fn),
            "pairwise_precision": round(float(tp / max(tp + fp, 1)), 5),
            "pairwise_recall": round(float(tp / max(total_truth_links, 1)), 5),
            "avg_predicted_matches_per_s1": round(float(total_pred_links / len(s1)), 3),
        }
        results.append(row)
        log(
            f"Th: {th:4.2f} | Macro F0.5: {row['macro_f0_5']:.4f} | Prec: {row['macro_precision']:.4f} | Rec: {row['macro_recall']:.4f} | Sng F0.5: {row['f0_5_singletons']:.4f} | Non-Sng: {row['f0_5_non_singletons']:.4f} | Pred: {row['predicted_links']:7d} | TP: {tp:6d} | FP: {fp:6d}"
        )

        if m["f0_5"] > best_f05:
            best_f05 = m["f0_5"]
            best_th = th
            best_row = row

    results_df = pd.DataFrame(results)
    results_df.to_csv(EXP_DIR / "threshold_results.csv", index=False)
    log(f"\nThreshold sweep saved to {EXP_DIR / 'threshold_results.csv'}")
    log(f"BEST THRESHOLD: {best_th:.2f} -> Official Macro F0.5: {best_row['macro_f0_5']:.5f}")

    # 5. Error Breakdown
    log("\n--- Step 5: Ceiling & Error Source Partition ---")
    # From 100k budget curve:
    raw_b5_miss = 15599  # Absent from Raw B5
    cap200_pruning_miss = 15418  # Present in Raw B5, but pruned by Cap-200
    model_tp = best_row["tp"]
    model_fn = best_row["fn"] - raw_b5_miss - cap200_pruning_miss
    model_fp = best_row["fp"]

    error_breakdown = {
        "total_ground_truth_links": total_truth_links,
        "A_raw_b5_blocking_miss": int(raw_b5_miss),
        "B_cap200_pruning_miss": int(cap200_pruning_miss),
        "C_model_false_negative_miss": int(model_fn),
        "D_model_false_positive": int(model_fp),
        "true_positives": int(model_tp),
        "best_threshold": float(best_th),
        "validation_s1_count": len(s1),
        "candidate_pairs_scored": total_candidate_pairs,
    }
    with open(EXP_DIR / "error_breakdown.json", "w", encoding="utf-8") as f:
        json.dump(error_breakdown, f, indent=2)

    log(f"Total True Positive Links: {total_truth_links:,}")
    log(f"  [A] Raw B5 Blocking Misses : {raw_b5_miss:7,d} ({100*raw_b5_miss/total_truth_links:5.2f}%)")
    log(f"  [B] Cap-200 Pruning Misses : {cap200_pruning_miss:7,d} ({100*cap200_pruning_miss/total_truth_links:5.2f}%)")
    log(f"  [C] Model False Negatives  : {model_fn:7,d} ({100*model_fn/total_truth_links:5.2f}%)")
    log(f"  [+] True Positives (Model) : {model_tp:7,d} ({100*model_tp/total_truth_links:5.2f}%)")
    log(f"  [D] Model False Positives  : {model_fp:7,d}")

    # 6. Save Evaluation JSON
    evaluation = {
        "experiment_id": "EXP-001",
        "description": "First ML Baseline: B5 blocking + deterministic Cap-200 + 22 RapidFuzz/token features + HistGradientBoosting",
        "validation_split": "100k_stratified_s1",
        "candidate_cap": CAP,
        "candidate_pairs_scored": total_candidate_pairs,
        "best_threshold": float(best_th),
        "official_macro_f0_5": best_row["macro_f0_5"],
        "macro_precision": best_row["macro_precision"],
        "macro_recall": best_row["macro_recall"],
        "f0_5_singletons": best_row["f0_5_singletons"],
        "f0_5_non_singletons": best_row["f0_5_non_singletons"],
        "tp": model_tp,
        "fp": model_fp,
        "fn": best_row["fn"],
        "predicted_links": best_row["predicted_links"],
        "avg_predicted_matches_per_s1": best_row["avg_predicted_matches_per_s1"],
        "blocking_recall": 0.95491,
        "cap200_recall": 0.91034,
        "runtimes": {
            "model_train_seconds": round(train_time, 1),
            "scoring_seconds": round(scoring_time, 1),
            "total_job_seconds": round(time.time() - t_job_start, 1),
        },
        "error_breakdown": error_breakdown,
    }
    with open(EXP_DIR / "evaluation.json", "w", encoding="utf-8") as f:
        json.dump(evaluation, f, indent=2)

    # 7. Append to experiments/experiments.csv
    exp_csv_path = PROJECT_ROOT / "experiments" / "experiments.csv"
    row_data = {
        "experiment_id": "EXP-001",
        "timestamp": time.strftime("%Y-%m-%d"),
        "description": "B5 blocker + Cap-200 + HistGradientBoosting baseline (22 features)",
        "validation_split": "100k_stratified_s1",
        "validation_f0_5": round(best_row["macro_f0_5"], 5),
        "macro_precision": round(best_row["macro_precision"], 5),
        "macro_recall": round(best_row["macro_recall"], 5),
        "f0_5_singletons": round(best_row["f0_5_singletons"], 5),
        "f0_5_non_singletons": round(best_row["f0_5_non_singletons"], 5),
        "blocking_recall": 0.91034,
        "candidate_pairs": total_candidate_pairs,
        "avg_candidates_per_s1": 185.58,
        "median_candidates_per_s1": 200.0,
        "p95_candidates_per_s1": 200.0,
        "max_candidates_per_s1": 200.0,
        "candidate_reduction_ratio": round(1 - total_candidate_pairs / (100000 * 10320219), 6),
        "runtime_seconds": round(time.time() - t_job_start, 1),
        "random_seed": SEED,
        "model": "HistGradientBoostingClassifier(max_depth=6)",
        "threshold": float(best_th),
        "notes": f"Cap-200 hard negatives, macro F0.5={best_row['macro_f0_5']:.4f}",
    }
    exp_df = pd.read_csv(exp_csv_path)
    # Filter out any prior EXP-001 if exists, keep EXP-000
    exp_df = exp_df[exp_df.experiment_id != "EXP-001"]
    exp_df = pd.concat([exp_df, pd.DataFrame([row_data])], ignore_index=True)
    exp_df.to_csv(exp_csv_path, index=False)
    log(f"Updated {exp_csv_path} with EXP-001.")

    log(f"\n=== EXP-001 Finished Successfully in {(time.time() - t_job_start)/60:.2f} min ===")


if __name__ == "__main__":
    main()
